### ISSUE TITLE
如何获取应用机密和应用id？

### ISSUE THREAD

**Issue by zhullyb** [lzx8589561/oneindex2-in#7]
原版的oneindex都会在输入应用id和应用机密那个页面提供一个链接以获取自己的应用id和应用机密，可是这个支持世纪互联的ONEINDEX却没有提供，所以我应该到哪里去获取呢？

**Comment by xtxzb2020** [comment]
到底怎么弄啊？

**Comment by Cyame** [comment]
在azure.cn的Dictionary创建一个应用，设置好权限之后复制密码和id。
具体步骤参见：[流程](https://luotianyi.vc/987.html)
